"""empty message

Revision ID: 331720def547
Revises: b6fddffb4eaf
Create Date: 2024-12-28 01:46:17.935466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "331720def547"
down_revision: Union[str, None] = "b6fddffb4eaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_form", "tag_or_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_form",
        sa.Column("tag_or_number", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
