"""empty message

Revision ID: b6fddffb4eaf
Revises: b0044af96d65
Create Date: 2024-12-28 00:13:49.272130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6fddffb4eaf"
down_revision: Union[str, None] = "b0044af96d65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tg_user",
        sa.Column(
            "is_bot_blocked", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tg_user", "is_bot_blocked")
    # ### end Alembic commands ###
